imagePullPolicy: Always
nodeSelector: {}

balancer:
  repository: iteratec/juice-balancer
  tag: latest
  replicas: 1
  resources:
    requests:
      memory: 256Mi
    limits:
      memory: 256Mi
  affinity: {}
  tolerations: []

juiceShop:
  # Set to -1 to remove the max Juice Shop instance cap
  maxInstances: 10
  # Specify a custom Juice Shop config
  # See the JuiceShop Config Docs for more detail: https://bkimminich.gitbooks.io/pwning-owasp-juice-shop/content/part1/customization.html#yaml-configuration-file
  config: |
    application:
      logo: JuiceShopCTF_Logo.png
      favicon: favicon_ctf.ico
      # showChallengeHints: false
      showVersionNumber: false
      # showHackingInstructor: false
      gitHubRibbon: false
    ctf:
      # showFlagsInNotifications: true

# Config for the redis deployment
# This is using: https://hub.helm.sh/charts/stable/redis
redis:
  cluster:
    slaveCount: 1
  # OpenShifts Default Security Context makes trouble with the security context
  # of the redis chart. Uncomment the next two lines to have it run on OpenShift.
  # securityContext:
  #   enabled: false

# Deletes unused JuiceShop instances after a configuable period of inactivity
juiceShopCleanup:
  repository: iteratec/juice-cleaner
  tag: latest
  enabled: true
  gracePeriod: 1d
  # cron in which the clean up job is run
  # defaults to once in an hour
  # change this if your grace period if shorter than 1 hour
  cron: '0 * * * *'
  resources:
    requests:
      memory: 256Mi
    limits:
      memory: 256Mi
  affinity: {}
  tolerations: []
