---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: juice-balancer
rules:
  - apiGroups: ['apps']
    resources: ['deployments']
    verbs: ['create', 'list']
  - apiGroups: [''] # "" indicates the core API group
    resources: ['services']
    verbs: ['create']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: juice-balancer
  namespace: default
subjects:
  - kind: ServiceAccount
    name: juice-balancer # Name is case sensitive
roleRef:
  kind: Role
  name: juice-balancer
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: juice-balancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: juice-balancer
spec:
  selector:
    matchLabels:
      app: juice-balancer
  template:
    metadata:
      labels:
        app: juice-balancer
    spec:
      serviceAccountName: juice-balancer
      containers:
        - name: juice-balancer
          image: juice-balancer:v18
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
