apiVersion: v1
kind: ConfigMap
metadata:
  name: juice-balancer-config
data:
  config.json: |
    {
      "port": 3000,
      "namespace": {{ .Release.Namespace | quote }},
      "redis": {
        "host": "{{ .Release.Name}}-redis-master",
        "port": 6379
      },
      "cookieParser": {}
    }
