apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: progress-watchdog
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "multi-juicer.progress-watchdog.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: progress-watchdog # Name is case sensitive
roleRef:
  kind: Role
  name: progress-watchdog
  apiGroup: rbac.authorization.k8s.io
