apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Release.Namespace | quote }}
  name: progress-watchdog
  labels:
    {{- include "multi-juicer.progress-watchdog.labels" . | nindent 4 }}
rules:
  - apiGroups: ['apps']
    resources: ['deployments']
    verbs: ['get', 'list', 'patch']
