apiVersion: v1
kind: Service
metadata:
  name: progress-watchdog
  labels:
    {{- include "multi-juicer.progress-watchdog.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    {{- include "multi-juicer.progress-watchdog.selectorLabels" . | nindent 4 }}
