{{- if and .Values.balancer.metrics.enabled .Values.balancer.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: juice-balancer
  labels:
    {{ include "multi-juicer.juice-balancer.labels" . | nindent 4 }}
    {{- with .Values.balancer.metrics.serviceMonitor.additionalLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "multi-juicer.juice-balancer.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: web
      path: '/balancer/metrics'
      basicAuth:
        username:
          name: juice-balancer-secret
          key: metricsBasicAuthUsername
        password:
          name: juice-balancer-secret
          key: metricsBasicAuthPassword
{{- end }}