apiVersion: v1
kind: ConfigMap
metadata:
  name: juice-shop-config
  labels:
    {{- include "multi-juicer.juice-shop.labels" . | nindent 4 }}
data:
  multi-juicer.yaml: |-
{{ .Values.juiceShop.config | indent 4 }}
