kind: Service
apiVersion: v1
metadata:
  name: multi-juicer-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/instance: juice-balancer-multi-juicer
    app.kubernetes.io/name: juice-balancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
