apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: juice-cleaner
  namespace: {{ .Release.Namespace | quote }}
subjects:
  - kind: ServiceAccount
    name: juice-cleaner # Name is case sensitive
roleRef:
  kind: Role
  name: juice-cleaner
  apiGroup: rbac.authorization.k8s.io