apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: 'cleanup-job'
spec:
  schedule: '0 * * * *'
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            name: 'cleanup-job'
        spec:
          serviceAccountName: 'juice-cleaner'
          containers:
            - image: 'j12934/juice-cleaner'
              name: 'cleanup-job'
              env:
                - name: NAMESPACE
                  value: {{ .Release.Namespace | quote }}
                - name: MAX_INACTIVE_DURATION
                  value: '3d'
                - name: REDIS_HOST
                  value: '{{ .Release.Name }}-redis-master'
                - name: REDIS_PORT
                  value: '6379'
                - name: REDIS_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: '{{ .Release.Name }}-redis'
                      key: redis-password
          restartPolicy: Never
