apiVersion: v1
kind: Secret
metadata:
  name: juice-balancer-secret
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  {{- if .Values.juiceBalancer.cookieParserSecret }}
  cookieParserSecret: {{ .Values.juiceBalancer.cookieParserSecret | b64enc | quote }}
  {{- else }}
  cookieParserSecret: {{ randAlphaNum 24 | b64enc | quote }}
  {{- end }}