apiVersion: v1
kind: Service
metadata:
  name: juice-balancer
  labels:
    app: 'juice-balancer'
    helm.sh/chart: {{ include "juicy-ctf.chart" . }}
spec:
  selector:
    app.kubernetes.io/name: juice-balancer
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - port: 3000
      name: web
