apiVersion: v1
kind: ConfigMap
metadata:
  name: juice-balancer-config
  labels:
    helm.sh/chart: {{ include "juicy-ctf.chart" . }}
data:
  config.json: |
    {
      "port": 3000,
      "namespace": {{ .Release.Namespace | quote }},
      "deploymentContext": {{ .Release.Name | quote }},
      "maxJuiceShopInstances": {{ .Values.juiceShop.maxInstances}},
      "redis": {
        "host": "{{ .Release.Name}}-redis-master",
        "port": 6379,
        "redis-secret-name": "{{ .Release.Name}}-ctf-redis"
      },
      "cookieParser": {
        "cookieName": {{ .Values.balancer.cookie.name | quote }},
        "secure": {{ .Values.balancer.cookie.secure }}
      },
      "admin": {
        "username": "admin"
      },
      "juiceShop": {
        "image": {{ .Values.juiceShop.image | quote }},
        "tag": {{ .Values.juiceShop.tag | quote }},
        "imagePullPolicy": {{ .Values.imagePullPolicy | quote }},
        "resources": {{ .Values.juiceShop.resources | toJson }}
      }
    }
