name: "Release Build"
on:
  release:
    types: [published]
env:
  CONTAINER_REGISTRY: ghcr.io/j12934
jobs:
  helmRelease:
    name: "Publish Helm Chart"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3

      - name: "Login to Package Registry"
        run: 'helm registry login --username ${{ github.actor }} --password "${{ secrets.GITHUB_TOKEN }}" ${{ env.CONTAINER_REGISTRY }}/helm/'

      - name: "Package Helm Chart"
        working-directory: helm/multi-juicer/
        run: |
          RELEASE_VERSION="${GITHUB_REF#refs/*/}"
          # Remove leading 'v' from git tag to create valid semver
          RELEASE_VERSION="${RELEASE_VERSION//v}"
          helm package --version "$RELEASE_VERSION" .

      - name: "Push Helm Chart"
        working-directory: helm/multi-juicer/
        run: |
          helm push multi-juicer-*.tgz oci://${{ env.CONTAINER_REGISTRY }}/helm/

  dockerBuilds:
    name: "Build"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        component:
          - progress-watchdog
          - cleaner
          - juice-balancer
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker Meta
        id: docker_meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.CONTAINER_REGISTRY }}/${{ matrix.component }}
          tags: |
            type=semver,pattern={{raw}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: ${{ env.CONTAINER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          context: ./${{ matrix.component }}
          file: ./${{ matrix.component }}/Dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
