on:
  release:
    types: [published]
name: "Publish Docker Images"
jobs:
  helmRelease:
    name: "Package Helm Chart"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: J12934/helm-gh-pages-action@v2.0.0
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          charts-folder: helm
          deploy-branch: gh-pages
  dockerBuilds:
    name: "Build"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        component:
          - progress-watchdog
          - cleaner
          - juice-balancer
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker Meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: iteratec/${{ matrix.component }}
          tag-semver: |
            {{ raw }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: "Set up QEMU"
        uses: docker/setup-qemu-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: ./${{ matrix.component }}
          file: ./${{ matrix.component }}/Dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
