on: [push, release]
name: 'CI'
jobs:
  progressWatchDog:
    name: ProgressWatchDog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build'n Push ProgressWatchDog
        uses: pangzineng/Github-Action-One-Click-Docker@bfb4a810c8cb823f4a87c24da145caa707e297e9
        env:
          DOCKER_IMAGE_NAME: juice-progress-watchdog
          DOCKER_NAMESPACE: iteratec
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        with:
          args: ./progress-watchdog/
  cleaner:
    name: Cleaner
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install Balancer
        run: |
          cd cleaner
          npm ci
      - name: Run Linter
        run: |
          cd cleaner
          npm run lint
      - name: Test Balancer
        run: |
          cd cleaner
          npm test -- --ci --color --verbose
      - name: Build'n Push Cleaner
        uses: pangzineng/Github-Action-One-Click-Docker@bfb4a810c8cb823f4a87c24da145caa707e297e9
        env:
          DOCKER_IMAGE_NAME: juice-cleaner
          DOCKER_NAMESPACE: iteratec
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        with:
          args: ./cleaner/
  balancer:
    name: Balancer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: 'Install & Build BalancerUI'
        run: |
          cd juice-balancer/ui
          npm ci
          npm run build
      - name: Install Balancer
        run: |
          cd juice-balancer
          npm ci
      - name: Run Linter
        run: |
          cd juice-balancer
          npm run lint
      - name: Test Balancer
        run: |
          cd juice-balancer
          npm test -- --ci --color --verbose
      - name: Build'n Push Balancer
        uses: pangzineng/Github-Action-One-Click-Docker@bfb4a810c8cb823f4a87c24da145caa707e297e9
        env:
          DOCKER_IMAGE_NAME: juice-balancer
          DOCKER_NAMESPACE: iteratec
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        with:
          args: ./juice-balancer/
