on: [push, pull_request]
name: "Tests"
jobs:
  cleaner:
    name: Cleaner
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: cleaner
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install Dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm test -- --ci --color --verbose

  balancer:
    name: Balancer
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: juice-balancer
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install Backend Dependencies
        run: npm ci
      - name: "Install UI Dependencies"
        working-directory: juice-balancer/ui
        run: npm ci
      - name: "Build UI"
        working-directory: juice-balancer/ui
        run: npm run build
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm test -- --ci --color --verbose

  progress-watchdog:
    name: ProgressWatchdog
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: progress-watchdog
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: "Lint"
        run: go vet
      - name: "Test"
        run: go test -cover
