apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: 'juicy-ctf'
  name: juice-cleaner
rules:
  - apiGroups: ['apps']
    resources: ['deployments']
    verbs: ['get', 'delete', 'list']
  - apiGroups: [''] # "" indicates the core API group
    resources: ['services']
    verbs: ['get', 'delete']
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: juice-cleaner
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: juice-cleaner
  namespace: 'juicy-ctf'
subjects:
  - kind: ServiceAccount
    name: juice-cleaner # Name is case sensitive
roleRef:
  kind: Role
  name: juice-cleaner
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  labels:
    job-name: 'cleanup-job'
  name: 'cleanup-job'
spec:
  selector:
    matchLabels:
      job-name: 'cleanup-job'
  template:
    metadata:
      labels:
        name: 'cleanup-job'
        job-name: 'cleanup-job'
    spec:
      serviceAccountName: 'juice-cleaner'
      containers:
        - image: 'j12934/juice-cleaner'
          name: 'cleanup-job'
          env:
            - name: NAMESPACE
              value: 'juicy-ctf'
            - name: MAX_INACTIVE_DURATION
              value: '30m'
            - name: REDIS_HOST
              value: 'juicy-ctf-redis-master'
            - name: REDIS_PORT
              value: '6379'
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: juicy-ctf-redis
                  key: redis-password
      restartPolicy: Never
